import type { NextPage } from "next";
import { useState, useEffect } from "react";
import { Button } from "@mantine/core";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getProducts } from "@services/Shopify";

const Home: NextPage = () => {
  const [products, setProducts] = useState<any>();

  const handleGetProducts = () => {
    const { data, error }: any = getProducts();
    if (data) console.log(data.data);
    console.log(error);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button onClick={handleGetProducts}>Hello World</Button>
      </main>
    </div>
  );
};

export default Home;
