/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import { useState, useEffect } from "react";
import { Button, Card, Box, Grid } from "@mantine/core";
import _ from "underscore";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getProducts } from "@services/Shopify";

const Home: NextPage = ({ data }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grid columns={3}>
          {data &&
            _.map(data.products.edges, (product: any) => {
              const { id, title, description, variants } = product.node;
              const url = variants.edges[0].node.image.url;
              return (
                <Card key={id}>
                  <h3>{title}</h3>
                  <img alt={title} src={url} />
                  <p>{description}</p>
                  <Button>Add to cart</Button>
                </Card>
              );
            })}
        </Grid>
      </main>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const { data }: any = await getProducts();

  return {
    props: { data },
  };
}
